server.port=8086

spring.application.name=payment-service
spring.datasource.url=jdbc:mysql://localhost:3306/smartcart_payment_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

razorpay.key_id=rzp_test_ScqHmVoI8WAn0s
razorpay.key_secret=66KXfW071C3daKqudMWWgw8I

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
